spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-ago.cr0vsnsa9i36.ap-northeast-2.rds.amazonaws.com:3306/ago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Thegreatejoo300!

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/ago_be
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  #  운영 장비에서는 절대 crate, create-drop, update 사용하면 안된다.
#  개발 초기 단계는 create 또는 update
#  테스트 서버는 update 또는 validate
#  스테이징과 운영 서버는 validate 또는 none

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  api-docs:
    path: /api/docs/open-api
  swagger-ui:
    path: /api/docs/swagger-ui

elasticsearch:
  local:
    ip: 127.0.0.1
    port: 9200
  prod:
    ip: 15.165.85.178
    port: 9200
